apiVersion: v1
data:
  passwords: |
    pwd1: 12
    pwd2: 13
    pwd3: 14
  usernames: |-
    uname1: hati
    uname2: ghora
    uname3: valluk
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-22T04:57:30Z"
  name: confg
  namespace: default
  resourceVersion: "5327"
  uid: 207c2299-a485-4833-8e7d-8299f468e4d4
